name = input("What is your name :\n")
surname = input("What is your surname :\n")
Year = input("What is your year :\n")
ID = input("What is your ID :\n")
print("\nname : %s" %name)
print("surname : %s" %surname)
print("Year :%s" % Year)
print("ID :%s" %ID)